/* ======================================
   QUIZ QUESTION BANK
   ====================================== */

const QUIZZES = {

  /* ──────── IDENTIFY PATTERN ──────── */
  identify: {
    title: 'Quiz: Identifikasi Pola',
    description: 'Lihat chart candlestick, pilih nama pola yang tepat.',
    questions: [
      {
        type: 'identify',
        question: 'Pola apa yang ditunjukkan di gambar ini?',
        visual: 'hammer',
        options: ['Hammer', 'Shooting Star', 'Doji', 'Hanging Man'],
        correct: 0,
        explain: '<b>Hammer</b> — body kecil di atas, lower shadow panjang minimal 2x body. Muncul di akhir downtrend sebagai sinyal bullish reversal.',
      },
      {
        type: 'identify',
        question: 'Pola apa ini?',
        visual: 'shooting_star',
        options: ['Inverted Hammer', 'Shooting Star', 'Gravestone Doji', 'Hanging Man'],
        correct: 1,
        explain: '<b>Shooting Star</b> — body kecil di bawah, upper shadow panjang. Muncul di puncak uptrend sebagai sinyal bearish reversal.',
      },
      {
        type: 'identify',
        question: 'Identifikasi pola 2-candle berikut:',
        visual: 'bullish_engulfing',
        options: ['Bullish Harami', 'Piercing Line', 'Bullish Engulfing', 'Tweezer Bottom'],
        correct: 2,
        explain: '<b>Bullish Engulfing</b> — candle bullish besar yang body-nya menelan penuh body candle bearish sebelumnya. Sinyal reversal bullish paling kuat.',
      },
      {
        type: 'identify',
        question: 'Pola 2-candle apa ini?',
        visual: 'bearish_engulfing',
        options: ['Dark Cloud Cover', 'Bearish Engulfing', 'Bearish Harami', 'Tweezer Top'],
        correct: 1,
        explain: '<b>Bearish Engulfing</b> — candle bearish besar menelan body candle bullish sebelumnya. Reversal bearish paling kuat.',
      },
      {
        type: 'identify',
        question: 'Pola 3-candle apa ini?',
        visual: 'morning_star',
        options: ['Three White Soldiers', 'Morning Star', 'Evening Star', 'Morning Doji Star'],
        correct: 1,
        explain: '<b>Morning Star</b> — 3 candle: bearish panjang → body kecil (star) dengan gap down → bullish panjang. Reversal bullish kuat.',
      },
      {
        type: 'identify',
        question: 'Pola ini:',
        visual: 'evening_star',
        options: ['Three Black Crows', 'Dark Cloud Cover', 'Evening Star', 'Morning Star'],
        correct: 2,
        explain: '<b>Evening Star</b> — 3 candle di puncak uptrend: bullish panjang → body kecil → bearish panjang. Reversal bearish kuat.',
      },
      {
        type: 'identify',
        question: 'Doji ini namanya:',
        visual: 'dragonfly_doji',
        options: ['Gravestone Doji', 'Northern Doji', 'Dragonfly Doji', 'Long-legged Doji'],
        correct: 2,
        explain: '<b>Dragonfly Doji</b> — open = close = high, dengan lower shadow panjang. Seperti huruf "T". Sinyal bullish reversal.',
      },
      {
        type: 'identify',
        question: 'Doji ini:',
        visual: 'gravestone_doji',
        options: ['Dragonfly Doji', 'Gravestone Doji', 'Four Price Doji', 'Northern Doji'],
        correct: 1,
        explain: '<b>Gravestone Doji</b> — open = close = low, dengan upper shadow panjang. Seperti "T" terbalik. Bearish reversal.',
      },
      {
        type: 'identify',
        question: 'Pola 3-candle ini:',
        visual: 'three_white_soldiers',
        options: ['Three White Soldiers', 'Three Black Crows', 'Morning Star', 'Three Line Strike'],
        correct: 0,
        explain: '<b>Three White Soldiers</b> — 3 candle bullish panjang berturut-turut, masing-masing close lebih tinggi, open di body sebelumnya. Konfirmasi reversal bullish.',
      },
      {
        type: 'identify',
        question: 'Pola ini:',
        visual: 'piercing_line',
        options: ['Bullish Engulfing', 'Piercing Line', 'Bullish Harami', 'Tweezer Bottom'],
        correct: 1,
        explain: '<b>Piercing Line</b> — C1 bearish panjang, C2 bullish yang open lebih rendah tapi close menembus > 50% body C1. Bukan full engulf (jika iya = Bullish Engulfing).',
      },
    ],
  },

  /* ──────── SIGNAL BULL/BEAR ──────── */
  signal: {
    title: 'Quiz: Bullish atau Bearish?',
    description: 'Tentukan sinyal dari masing-masing pola.',
    questions: [
      {
        type: 'signal',
        question: 'Hammer di akhir downtrend = sinyal apa?',
        options: ['🟢 Bullish Reversal', '🔴 Bearish Reversal', '⚪ Continuation', '❓ Tidak ada sinyal'],
        correct: 0,
        explain: 'Hammer di downtrend = sinyal <b>Bullish Reversal</b>. Seller kehilangan tenaga, buyer mulai ambil alih.',
      },
      {
        type: 'signal',
        question: 'Shooting Star di puncak uptrend = ?',
        options: ['🟢 Bullish Reversal', '🔴 Bearish Reversal', '⚪ Neutral', '🎯 Continuation bullish'],
        correct: 1,
        explain: 'Shooting Star di puncak uptrend = <b>Bearish Reversal</b>. Buyer ditolak di upper shadow panjang, seller mulai kontrol.',
      },
      {
        type: 'signal',
        question: 'Bullish Engulfing — kapan signalnya valid?',
        options: [
          'Di akhir downtrend',
          'Di puncak uptrend',
          'Di tengah sideways',
          'Kapan saja, selalu valid',
        ],
        correct: 0,
        explain: 'Bullish Engulfing valid <b>di akhir downtrend</b>. Di sideways atau uptrend, ini bukan sinyal reversal — hanya noise.',
      },
      {
        type: 'signal',
        question: 'Hanging Man bentuknya sama dengan Hammer. Apa yang membedakan?',
        options: [
          'Warna body',
          'Panjang shadow',
          'Context (trend sebelumnya)',
          'Timeframe',
        ],
        correct: 2,
        explain: '<b>Context</b> yang membedakan. Hammer di downtrend = bullish reversal. Hanging Man di uptrend = bearish reversal. Bentuk identik!',
      },
      {
        type: 'signal',
        question: 'Morning Star = ?',
        options: [
          '🟢 Bullish Reversal',
          '🔴 Bearish Reversal',
          '🟢 Bullish Continuation',
          '🔴 Bearish Continuation',
        ],
        correct: 0,
        explain: '<b>Morning Star</b> = bullish reversal di akhir downtrend. 3 candle: transisi bearish → indecision → bullish.',
      },
      {
        type: 'signal',
        question: 'Evening Star = ?',
        options: [
          '🟢 Bullish Reversal',
          '🔴 Bearish Reversal',
          '⚪ Indecision',
          '🎯 Continuation',
        ],
        correct: 1,
        explain: '<b>Evening Star</b> = bearish reversal di puncak uptrend. 3 candle: bullish → indecision → bearish.',
      },
      {
        type: 'signal',
        question: 'Bearish Harami muncul di uptrend. Ini sinyal:',
        options: [
          'Kuat: langsung SELL',
          'Warning: momentum buyer melemah, tunggu konfirmasi',
          'Bullish continuation',
          'Ignore, pola lemah',
        ],
        correct: 1,
        explain: '<b>Harami = early warning</b>, BUKAN sinyal kuat. Jangan entry tanpa candle konfirmasi yang menembus low Harami.',
      },
      {
        type: 'signal',
        question: 'Dragonfly Doji di support = ?',
        options: [
          'Bearish continuation',
          'Bullish reversal',
          'Random noise',
          'Wait and see',
        ],
        correct: 1,
        explain: '<b>Dragonfly Doji</b> di support = bullish reversal signal yang kuat. Seller push turun tapi buyer mengambil alih total.',
      },
      {
        type: 'signal',
        question: 'Three Black Crows di top = ?',
        options: [
          'Bullish continuation',
          'Bearish reversal kuat',
          'Hanya koreksi sementara',
          'Ignore',
        ],
        correct: 1,
        explain: '<b>Three Black Crows</b> = 3 candle bearish panjang berturut di puncak = konfirmasi bearish reversal sangat kuat.',
      },
      {
        type: 'signal',
        question: 'Gravestone Doji di resistance:',
        options: [
          'Bullish signal',
          'Bearish reversal signal',
          'Continuation',
          'Tidak ada arti',
        ],
        correct: 1,
        explain: '<b>Gravestone Doji</b> di resistance = bearish reversal. Buyer coba push ke atas tapi gagal total.',
      },
    ],
  },

  /* ──────── ENTRY POINT ──────── */
  entry: {
    title: 'Quiz: Trading Rules & Entry',
    description: 'Uji pemahaman soal entry, stop loss, dan manajemen risiko.',
    questions: [
      {
        type: 'entry',
        question: 'Setelah Hammer muncul di downtrend, kapan entry BUY yang paling aman?',
        options: [
          'Langsung saat Hammer close',
          'Ketika candle berikutnya close di atas high Hammer (konfirmasi)',
          'Saat harga break ke bawah low Hammer',
          'Entry di low Hammer',
        ],
        correct: 1,
        explain: 'Tunggu <b>konfirmasi</b>: candle berikutnya close di atas high Hammer. Ini mengurangi false signal. Entry agresif (langsung saat Hammer close) punya win-rate lebih rendah.',
      },
      {
        type: 'entry',
        question: 'Stop loss untuk trade Hammer ditempatkan di mana?',
        options: [
          'Di high Hammer',
          'Di body Hammer',
          'Di bawah low Hammer + buffer',
          'Di close Hammer',
        ],
        correct: 2,
        explain: 'Stop loss di bawah <b>low Hammer</b> (lower shadow) + buffer beberapa pips. Kalau harga tembus low Hammer, berarti pola failed.',
      },
      {
        type: 'entry',
        question: 'Risk-reward minimum yang disarankan untuk trade candlestick pattern?',
        options: [
          '1:1',
          '1:2',
          '2:1',
          '1:0.5',
        ],
        correct: 1,
        explain: 'Minimum <b>1:2 Risk-Reward</b>. Artinya jika risk 50 pips, target minimum 100 pips. Win-rate candlestick pattern ~50-60%, jadi RR 1:2 memastikan profitabilitas jangka panjang.',
      },
      {
        type: 'entry',
        question: 'Pada Bullish Engulfing, entry konservatif yang tepat?',
        options: [
          'Langsung beli saat close candle 2',
          'Beli di pullback ke midpoint candle 2',
          'Beli saat breakdown low',
          'Tunggu 10 candle',
        ],
        correct: 1,
        explain: 'Entry <b>konservatif</b>: tunggu pullback ke midpoint atau low candle 2. Risk:reward lebih baik dari entry agresif saat close.',
      },
      {
        type: 'entry',
        question: 'Timeframe mana yang paling reliable untuk candlestick pattern?',
        options: [
          'M1-M5 (scalping)',
          'M15-H1',
          'H4-Daily',
          'Weekly sajalah',
        ],
        correct: 2,
        explain: '<b>H4-Daily</b> paling reliable. Timeframe kecil punya terlalu banyak noise. Weekly juga reliable tapi sinyal jarang muncul.',
      },
      {
        type: 'entry',
        question: 'Morning Star — stop loss di mana?',
        options: [
          'Di low candle 1',
          'Di low candle 2 (star)',
          'Di high candle 3',
          'Di open candle 1',
        ],
        correct: 1,
        explain: 'Stop loss di bawah <b>low candle 2 (star)</b> — titik terendah dari pola. Jika tembus = pola failed.',
      },
      {
        type: 'entry',
        question: 'Konfirmasi tambahan apa yang paling penting untuk validasi pola?',
        options: [
          'Support/Resistance level',
          'Waktu di jam market Amerika',
          'Jumlah candle sebelumnya',
          'Warna chart',
        ],
        correct: 0,
        explain: '<b>Support/Resistance</b> adalah konfirmasi terpenting. Hammer di support = 10x lebih kuat dari Hammer di tengah range.',
      },
      {
        type: 'entry',
        question: 'Apa yang HARUS dilakukan SEBELUM entry berdasarkan candlestick?',
        options: [
          'Cek astrologi hari itu',
          'Identifikasi trend, support/resistance, dan konfirmasi volume',
          'Entry max size untuk maksimal profit',
          'Konsultasi grup Telegram',
        ],
        correct: 1,
        explain: 'Sebelum entry: <b>identifikasi trend</b> (context), <b>support/resistance</b>, dan <b>konfirmasi volume</b>. Candlestick tanpa context = setup kurang berkualitas.',
      },
      {
        type: 'entry',
        question: 'Bearish Engulfing muncul di tengah sideways (bukan uptrend). Tindakanmu?',
        options: [
          'Langsung SELL, pola kuat',
          'Skip — context tidak sesuai (butuh uptrend sebelumnya)',
          'BUY sebaliknya',
          'Tambah position besar',
        ],
        correct: 1,
        explain: 'Pola reversal butuh <b>trend yang jelas sebelumnya</b>. Di sideways, bearish engulfing hanya noise, bukan reversal valid. Skip atau tunggu context yang tepat.',
      },
      {
        type: 'entry',
        question: 'Position sizing untuk trade candlestick di akun $10,000 dengan risk 1%?',
        options: [
          'Risk $100 per trade',
          'Risk $1000 per trade',
          'All-in $10,000',
          'Risk $10 per trade (terlalu kecil)',
        ],
        correct: 0,
        explain: 'Risk 1% dari $10,000 = <b>$100 per trade</b>. Ini standar money management — berapa pun confident sama pattern, JANGAN risk lebih dari 1-2% per trade.',
      },
    ],
  },

  /* ──────── MASTER QUIZ (MIXED) ──────── */
  master: {
    title: 'Master Quiz 🏆',
    description: 'Quiz komprehensif — semua pola dan konsep. 15 pertanyaan acak.',
    questions: [
      {
        type: 'identify',
        question: 'Identifikasi pola ini:',
        visual: 'hammer',
        options: ['Shooting Star', 'Inverted Hammer', 'Hammer', 'Hanging Man'],
        correct: 2,
        explain: 'Hammer — body kecil di atas, lower shadow panjang, di downtrend.',
      },
      {
        type: 'signal',
        question: 'Inverted Hammer di downtrend = ?',
        options: ['Bearish reversal', 'Bullish reversal (butuh konfirmasi)', 'Continuation', 'Neutral'],
        correct: 1,
        explain: 'Inverted Hammer = bullish reversal, tapi butuh konfirmasi karena sinyalnya lebih lemah dari Hammer biasa.',
      },
      {
        type: 'identify',
        question: 'Pola 2-candle ini:',
        visual: 'dark_cloud_cover',
        options: ['Bearish Engulfing', 'Dark Cloud Cover', 'Bearish Harami', 'Tweezer Top'],
        correct: 1,
        explain: 'Dark Cloud Cover — C2 bearish yang open gap up tapi close > 50% body C1 ke bawah. Belum full engulf.',
      },
      {
        type: 'entry',
        question: 'Untuk Evening Star di Daily XAUUSD di ATH, stop loss terbaik?',
        options: [
          'Di atas high candle 2 (star)',
          'Di low candle 3',
          'Di mid candle 1',
          'Tidak perlu stop loss',
        ],
        correct: 0,
        explain: 'SL di atas high candle 2 (star) — titik tertinggi pola. Kalau tembus, pola invalid.',
      },
      {
        type: 'signal',
        question: 'Pola mana yang paling reliable untuk bullish reversal?',
        options: [
          'Hammer',
          'Bullish Harami',
          'Morning Star',
          'Bullish Belt Hold',
        ],
        correct: 2,
        explain: 'Morning Star reliability ⭐⭐⭐⭐⭐. Kombinasi 3 candle dengan gap + momentum confirmation = signal paling clean.',
      },
      {
        type: 'identify',
        question: 'Doji ini:',
        visual: 'dragonfly_doji',
        options: ['Gravestone Doji', 'Four Price Doji', 'Dragonfly Doji', 'Long-legged Doji'],
        correct: 2,
        explain: 'Dragonfly Doji — bentuk huruf T (open = close = high, lower shadow panjang).',
      },
      {
        type: 'signal',
        question: 'Perbedaan kunci Hammer vs Hanging Man?',
        options: [
          'Bentuk berbeda',
          'Warna berbeda',
          'Context trend berbeda (Hammer: downtrend, Hanging Man: uptrend)',
          'Tidak ada perbedaan',
        ],
        correct: 2,
        explain: 'Bentuknya IDENTIK — yang beda adalah context/trend sebelumnya. Hammer = di downtrend (bullish reversal). Hanging Man = di uptrend (bearish reversal).',
      },
      {
        type: 'entry',
        question: 'Setup ideal untuk trade Morning Star?',
        options: [
          'Muncul di tengah uptrend',
          'Muncul di support kunci + RSI oversold + volume besar di C3',
          'Muncul di M1 timeframe',
          'Muncul tanpa konteks apa pun',
        ],
        correct: 1,
        explain: 'Setup ideal: Morning Star di SUPPORT kunci, dengan RSI oversold + bullish divergence, dan volume besar di candle 3 (konfirmasi).',
      },
      {
        type: 'identify',
        question: 'Pola 3-candle bearish:',
        visual: 'three_black_crows',
        options: ['Evening Star', 'Three Black Crows', 'Bearish Engulfing x3', 'Dark Cloud x3'],
        correct: 1,
        explain: 'Three Black Crows — 3 candle bearish panjang berturut-turut dengan close progresif lebih rendah.',
      },
      {
        type: 'signal',
        question: 'Piercing Line vs Bullish Engulfing, mana lebih kuat?',
        options: [
          'Piercing Line',
          'Bullish Engulfing',
          'Sama saja',
          'Tergantung timeframe',
        ],
        correct: 1,
        explain: 'Bullish Engulfing lebih kuat — body menelan PENUH body C1. Piercing Line hanya > 50% (belum full engulf).',
      },
      {
        type: 'entry',
        question: 'Apa fungsi utama candle ke-3 dalam Morning Star / Evening Star?',
        options: [
          'Decoration',
          'Konfirmasi reversal (momentum baru mengambil alih)',
          'Stop loss level',
          'Waktu tunggu',
        ],
        correct: 1,
        explain: 'Candle 3 = <b>konfirmasi reversal</b>. Tanpa C3 yang kuat, pola hanya indecision (C2 doji) tanpa arah baru.',
      },
      {
        type: 'signal',
        question: 'Tweezer Bottom terbentuk ketika:',
        options: [
          '2 candle punya close sama',
          '2 candle punya low IDENTIK',
          '2 candle bergerak sama',
          '2 candle berwarna sama',
        ],
        correct: 1,
        explain: 'Tweezer Bottom = 2 candle dengan LOW identik (atau selisih < 5 pips). Tes support 2x gagal break = support kuat.',
      },
      {
        type: 'entry',
        question: 'Pola muncul tapi volume LEMAH — tindakan terbaik?',
        options: [
          'Entry agresif',
          'Skip / tunggu sinyal dengan volume konfirmasi',
          'Entry dengan size double',
          'Ignore volume sepenuhnya',
        ],
        correct: 1,
        explain: 'Volume rendah = konfirmasi lemah. Pola candlestick + volume besar = sinyal valid. Volume lemah = skip atau tunggu setup lain.',
      },
      {
        type: 'signal',
        question: 'Apa itu "context" dalam trading candlestick?',
        options: [
          'Nama trader legend',
          'Trend & level S/R sebelum pola muncul',
          'Jam trading',
          'Jenis broker',
        ],
        correct: 1,
        explain: 'Context = kondisi pasar (trend, support/resistance, indikator) saat pola muncul. Pola TANPA context = tidak bermakna.',
      },
      {
        type: 'identify',
        question: 'Pola 2-candle bullish ini:',
        visual: 'bullish_harami',
        options: ['Bullish Engulfing', 'Piercing Line', 'Bullish Harami', 'Tweezer Bottom'],
        correct: 2,
        explain: 'Bullish Harami — C2 bullish kecil FULL di dalam body C1 bearish besar. "Pregnant" — momentum bearish kehabisan tenaga.',
      },
    ],
  },

  /* ──────── CHART PATTERNS ──────── */
  chart_patterns: {
    title: 'Quiz: Chart Patterns Klasik',
    description: 'Identifikasi dan trading rules untuk H&S, Double Top/Bottom, Triangles, Flags.',
    questions: [
      {
        type: 'signal',
        question: 'Head and Shoulders (H&S) adalah sinyal apa?',
        options: ['Bullish Reversal', 'Bearish Reversal', 'Bullish Continuation', 'Neutral'],
        correct: 1,
        explain: '<b>H&S = Bearish Reversal</b> di puncak uptrend. 3 puncak (LS, Head lebih tinggi, RS lebih rendah) + breakdown neckline = konfirmasi.',
      },
      {
        type: 'entry',
        question: 'Kapan entry SELL yang valid untuk pola H&S?',
        options: [
          'Saat Right Shoulder terbentuk',
          'Saat Head terbentuk',
          'Saat close di bawah neckline (atau retest neckline setelah breakdown)',
          'Saat Left Shoulder selesai',
        ],
        correct: 2,
        explain: 'Entry H&S = <b>setelah breakdown neckline</b>. Lebih baik: tunggu retest neckline dari bawah = entry dengan R:R lebih baik.',
      },
      {
        type: 'signal',
        question: 'Apa yang membedakan Ascending Triangle dari Symmetrical Triangle?',
        options: [
          'Ascending Triangle punya resistance flat + lower trendline naik (higher lows)',
          'Ascending Triangle punya support flat + upper trendline turun',
          'Tidak ada perbedaan',
          'Ascending Triangle hanya terjadi di downtrend',
        ],
        correct: 0,
        explain: '<b>Ascending Triangle:</b> Resistance FLAT (horizontal) + lower trendline naik (higher lows). Menunjukkan buyer agresif, biasanya breakout ke atas.',
      },
      {
        type: 'signal',
        question: 'Bull Flag muncul setelah rally tajam. Sinyal apa yang ditunjukkan?',
        options: [
          'Bearish reversal — waktu sell',
          'Bullish continuation — lanjutan naik setelah konsolidasi',
          'Neutral — tidak ada sinyal',
          'Breakout ke bawah',
        ],
        correct: 1,
        explain: '<b>Bull Flag = Bullish Continuation</b>. Flagpole = rally awal. Flag = konsolidasi (turun miring). Breakout ke atas = lanjutan rally.',
      },
      {
        type: 'entry',
        question: 'Target profit (measured move) untuk Double Bottom di mana?',
        options: [
          'Setara jarak dari lembah ke neckline, diukur dari neckline ke atas',
          'Setara jarak dari puncak ke neckline',
          '50% dari swing range',
          'Tidak ada target tertentu',
        ],
        correct: 0,
        explain: 'Double Bottom target = <b>Neckline + (Neckline − Bottom)</b>. Contoh: Bottom di 1950, Neckline 2000 → target 2050.',
      },
      {
        type: 'signal',
        question: 'Rising Wedge memberikan sinyal apa?',
        options: [
          'Bullish — harga naik terus',
          'Bearish — price bergerak naik tapi momentum habis, akan breakdown',
          'Neutral sideways',
          'Bullish continuation',
        ],
        correct: 1,
        explain: '<b>Rising Wedge = Bearish</b>. Meski harga naik, 2 trendline konvergen ke atas menunjukkan momentum buyer habis. Breakdown biasanya tajam.',
      },
      {
        type: 'entry',
        question: 'Volume ideal saat breakout dari Symmetrical Triangle?',
        options: [
          'Volume rendah — quiet breakout lebih valid',
          'Volume spike besar — mengkonfirmasi kekuatan breakout',
          'Volume sama dengan sebelumnya',
          'Volume tidak relevan untuk triangle',
        ],
        correct: 1,
        explain: '<b>Breakout valid = Volume spike besar</b>. Breakout tanpa volume = sering false breakout. Rule: "Breakout dengan volume = go, tanpa volume = wait".',
      },
      {
        type: 'signal',
        question: 'Inverse Head & Shoulders di akhir downtrend memberikan sinyal?',
        options: ['Bearish lanjutan', 'Bullish reversal', 'Sideways lanjutan', 'Tidak bermakna'],
        correct: 1,
        explain: '<b>Inverse H&S = Bullish Reversal</b>. 3 lembah (LS, Head lebih dalam, RS lebih tinggi dari Head) + breakout neckline = konfirmasi bullish.',
      },
      {
        type: 'entry',
        question: 'Mana yang lebih reliable: Double Top atau Hammer tunggal?',
        options: [
          'Hammer — lebih sederhana',
          'Double Top — dikonfirmasi dua kali oleh pasar',
          'Sama saja',
          'Tergantung timeframe',
        ],
        correct: 1,
        explain: '<b>Double Top lebih reliable</b>. Level resistance dikonfirmasi DUA KALI + butuh breakdown neckline. Ini akumulasi konfirmasi yang lebih kuat dari single candle.',
      },
      {
        type: 'signal',
        question: 'Falling Wedge memberikan sinyal?',
        options: ['Bearish continuation', 'Bullish reversal atau bullish continuation', 'Bearish reversal', 'Neutral'],
        correct: 1,
        explain: '<b>Falling Wedge = Bullish</b>. Meski harga turun, momentum seller melemah (wedge menyempit). Breakout ke atas = bullish yang sering explosive.',
      },
    ],
  },

  /* ──────── INDICATORS ──────── */
  indicators: {
    title: 'Quiz: Technical Indicators',
    description: 'RSI, MACD, Bollinger Bands, dan Moving Averages.',
    questions: [
      {
        type: 'signal',
        question: 'RSI > 70 menandakan apa?',
        options: ['Oversold — beli segera', 'Overbought — bersiap untuk koreksi', 'Bullish kuat — hold', 'Tidak ada arti'],
        correct: 1,
        explain: '<b>RSI > 70 = Overbought</b>. Harga naik terlalu cepat. Ini WARNING untuk potensi koreksi — kombinasikan dengan bearish candlestick pattern untuk entry sell.',
      },
      {
        type: 'entry',
        question: 'RSI Bullish Divergence artinya?',
        options: [
          'Harga buat higher high, RSI buat higher high',
          'Harga buat lower low, RSI buat higher low — momentum seller melemah',
          'RSI dan harga bergerak searah',
          'RSI di atas 70',
        ],
        correct: 1,
        explain: '<b>Bullish Divergence:</b> Harga cetak lower low baru tapi RSI cetak higher low = momentum bearish melemah. Sinyal bullish reversal yang kuat.',
      },
      {
        type: 'signal',
        question: 'MACD Line memotong ke atas Signal Line dari bawah zero = ?',
        options: [
          'Bearish signal — sell',
          'Bullish signal — buy (lebih kuat karena di bawah zero)',
          'Neutral signal',
          'Exit signal',
        ],
        correct: 1,
        explain: '<b>MACD Cross Bullish di bawah zero</b> = sinyal beli yang paling kuat. MACD line memotong ke atas signal line DI BAWAH nol menunjukkan momentum sudah dari bearish ke bullish.',
      },
      {
        type: 'entry',
        question: 'Bollinger Bands Squeeze menandakan?',
        options: [
          'Trend kuat sedang berlangsung',
          'Volatility rendah — akan ada breakout besar segera',
          'Market sideways permanen',
          'Tidak ada arti khusus',
        ],
        correct: 1,
        explain: '<b>BB Squeeze = Energy Terkompresi</b>. Bands menyempit = volatility sangat rendah. Ini biasanya SEBELUM breakout besar. Pantau arah breakout untuk posisi.',
      },
      {
        type: 'signal',
        question: 'Golden Cross (SMA 50 cross ke atas SMA 200) = sinyal apa?',
        options: [
          'Bearish jangka panjang — sell',
          'Bullish jangka panjang — buy signal',
          'Short term reversal',
          'Neutral — tunggu konfirmasi',
        ],
        correct: 1,
        explain: '<b>Golden Cross = Bullish jangka panjang</b>. Ketika SMA 50 (mid-term) cross di atas SMA 200 (long-term) = pergeseran tren besar dari bearish ke bullish.',
      },
      {
        type: 'entry',
        question: 'Untuk sizing Stop Loss menggunakan ATR, angka yang tepat?',
        options: [
          'Stop di 0.1× ATR — sangat ketat',
          'Stop di 1.5× ATR — menghindari noise sambil masih reasonable',
          'Stop di 10× ATR — terlalu lebar',
          'ATR tidak relevan untuk SL',
        ],
        correct: 1,
        explain: '<b>1.5-2× ATR</b> adalah standar untuk stop loss. Cukup lebar untuk menghindari normal market noise, tapi tidak terlalu lebar yang merusak R:R.',
      },
      {
        type: 'signal',
        question: 'Harga menyentuh Lower Bollinger Band + muncul Hammer. Ini setup?',
        options: [
          'Sell signal kuat',
          'Buy signal kuat — double confirmation',
          'Neutral — tunggu lebih banyak konfirmasi',
          'Abaikan — BB tidak reliable',
        ],
        correct: 1,
        explain: '<b>Double confirmation = setup kuat!</b> Lower BB = harga "murah" secara statistik. Hammer = reversal candle. Kombinasi = buy signal dengan probabilitas tinggi.',
      },
      {
        type: 'entry',
        question: 'MA 200 Daily sering menjadi:',
        options: [
          'Level yang diabaikan oleh trader',
          'Support/Resistance paling diperhatikan institusional dan level kunci global',
          'Hanya untuk investor jangka panjang',
          'Indikator yang terlalu lambat untuk dipakai',
        ],
        correct: 1,
        explain: '<b>MA 200 Daily</b> = level kunci global. Fund manager, bank, dan institusi memperhatikan ini. Bounce dari MA200 + bullish candle = setup premium.',
      },
    ],
  },

  /* ──────── S/R & FIBONACCI ──────── */
  sr_fibonacci: {
    title: 'Quiz: Support, Resistance & Fibonacci',
    description: 'Konsep S/R, role reversal, dan level Fibonacci.',
    questions: [
      {
        type: 'signal',
        question: 'Support yang ditembus ke bawah kemudian menjadi?',
        options: [
          'Tetap support',
          'Resistance baru (Role Reversal)',
          'Hilang — tidak relevan lagi',
          'Target take profit',
        ],
        correct: 1,
        explain: '<b>Role Reversal:</b> Support yang breakdown menjadi resistance baru. Ini sangat reliable — harga sering kembali test level tersebut dari bawah sebelum lanjut turun.',
      },
      {
        type: 'entry',
        question: 'Fibonacci 61.8% disebut "Golden Ratio" karena?',
        options: [
          'Angka keberuntungan',
          'Level di mana pullback paling sering berakhir dan trend dilanjutkan',
          'Level stop loss default',
          'Hanya nama statistik',
        ],
        correct: 1,
        explain: '<b>61.8% = Golden Ratio</b>. Secara empiris, pullback dalam trend kuat paling sering berakhir di 61.8% Fibonacci. Level ini paling ditunggu trader profesional.',
      },
      {
        type: 'signal',
        question: 'Angka psikologi seperti 2000, 2100 untuk XAUUSD menjadi S/R karena?',
        options: [
          'Kebetulan semata',
          'Banyak order (buy limit, sell limit, stop loss) menumpuk di angka bulat',
          'Ditentukan oleh pemerintah',
          'Hanya berlaku untuk forex',
        ],
        correct: 1,
        explain: 'Round numbers menarik banyak order secara psikologis — trader menempatkan entry/exit di angka bulat. Akumulasi order = support/resistance nyata.',
      },
      {
        type: 'entry',
        question: 'Cara paling optimal menggunakan Fibonacci retracement?',
        options: [
          'Masuk saat harga mendekati level Fibonacci, tanpa konfirmasi',
          'Tunggu harga capai level Fib + muncul candlestick pattern konfirmasi + RSI oversold',
          'Hanya gunakan level 50%',
          'Gunakan Fibonacci tanpa cek trend sebelumnya',
        ],
        correct: 1,
        explain: '<b>Fibonacci + Candlestick + RSI = Setup Premium</b>. Jangan entry semata-mata karena harga di level Fib — tunggu candlestick pattern sebagai konfirmasi.',
      },
      {
        type: 'signal',
        question: 'Fibonacci Extension digunakan untuk?',
        options: [
          'Menentukan Stop Loss',
          'Menentukan Target Profit (Take Profit) setelah breakout',
          'Identifikasi trend',
          'Ukur volatility',
        ],
        correct: 1,
        explain: '<b>Fibonacci Extension = Target Profit</b>. Setelah breakout, level 127.2% dan 161.8% sering menjadi target harga berikutnya.',
      },
      {
        type: 'entry',
        question: '"Confluence" dalam trading S/R + Fibonacci berarti?',
        options: [
          'Menggunakan banyak indikator sekaligus secara random',
          'Multiple levels bertemu di satu zona — meningkatkan probabilitas reversal/bounce',
          'Strategi scalping agresif',
          'Konfirmasi dari berita fundamental',
        ],
        correct: 1,
        explain: '<b>Confluence = Multiple Confirmation</b>. Fib 61.8% + S/R horizontal + MA200 + round number di satu area = "zona ajaib" dengan probabilitas bounce/reversal sangat tinggi.',
      },
    ],
  },
};
